[build]
  command = "npm install"
  functions = "functions"

[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions."functions/bot"]
  included_files = ["functions/bot.js"]
  external_node_modules = ["telegraf", "moment-timezone", "node-cron"]
  timeout = 30