name: Daily Salary Notification

on:
  schedule:
    # This will run at 11:19 UTC (13:19 Kyiv time during standard time)
    - cron: '21 13 * * *'
    # This will run at 10:19 UTC (13:19 Kyiv time during daylight saving time)
    - cron: '21 14 * * *'
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  trigger_netlify_function:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Netlify Function
      run: |
        curl -X POST ${{ secrets.NETLIFY_FUNCTION_URL }} \
        -H "Content-Type: application/json" \
        -d '{"trigger": "daily_notification"}'
      env:
        NETLIFY_FUNCTION_URL: ${{ secrets.NETLIFY_FUNCTION_URL }}