name: Daily Salary Notification

on:
  schedule:
    - cron: '25 22 * * *'  # 16:27 Kyiv time during winter (UTC+2)
    - cron: '25 23 * * *'  # 16:27 Kyiv time during summer (UTC+3)
  workflow_dispatch:  # This allows manual triggering

jobs:
  trigger-salary-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Curl request and check response
      run: |
        echo "Sending request to ${{ secrets.NETLIFY_FUNCTION_URL }}"
        response=$(curl -v -X POST ${{ secrets.NETLIFY_FUNCTION_URL }} \
        -H "Content-Type: application/json" \
        -d '{"trigger": "daily_notification", "message":{"text":"/when_salary"}}')
        echo "Response: $response"
        echo "Response length: ${#response}"
        curl_exit_code=$?
        echo "cURL exit code: $curl_exit_code"
        
        if [[ -z "$response" ]]; then
          echo "Error: No response received"
          exit 1
        elif [[ $response == *"Daily notification sent successfully"* ]]; then
          echo "Daily notification sent successfully"
        else
          echo "Unexpected response from Netlify function"
          echo "Full response: $response"
          exit 1
        fi
      env:
        NETLIFY_FUNCTION_URL: ${{ secrets.NETLIFY_FUNCTION_URL }}